# Generated by Django 5.2.8 on 2025-11-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('skills', models.TextField(help_text='Comma-separated skills, e.g. React, Node.js')),
                ('min_budget', models.IntegerField(blank=True, null=True)),
                ('max_budget', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('experience_level', models.CharField(choices=[('Any', 'Any'), ('Junior', 'Junior'), ('Mid-level', 'Mid-level'), ('Senior', 'Senior')], default='Any', max_length=20)),
                ('project_type', models.CharField(choices=[('Fixed Price', 'Fixed Price'), ('Hourly', 'Hourly')], default='Fixed Price', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('draft', 'Draft'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
