const messagingStyles = {
  page: { padding: "24px", backgroundColor: "#f8fafc", minHeight: "100vh" },
  layout: { display: "grid", gridTemplateColumns: "360px minmax(0, 1fr)", gap: "24px", width: "min(1600px, 100%)", margin: "0 auto" },
  sidebar: { width: "100%", backgroundColor: "#fff", borderRadius: "16px", border: "1px solid #e2e8f0", display: "flex", flexDirection: "column", height: "calc(100vh - 160px)" },
  sidebarHeader: { padding: "20px", fontWeight: 700, borderBottom: "1px solid #f1f5f9", color: "#0f172a" },
  searchBar: { padding: "14px 20px", borderBottom: "1px solid #f1f5f9", display: "flex", alignItems: "center", gap: "10px" },
  icon: { display: "flex", alignItems: "center", color: "#94a3b8" },
  searchInput: { border: "none", outline: "none", width: "100%", background: "transparent", fontSize: "14px", color: "#334155" },
  list: { flex: 1, overflowY: "auto" },
  row: { width: "100%", border: "none", borderBottom: "1px solid #f8fafc", padding: "16px 20px", display: "flex", gap: "14px", alignItems: "center", cursor: "pointer", background: "transparent" },
  avatar: { width: "42px", height: "42px", borderRadius: "50%", objectFit: "cover", border: "1px solid #e2e8f0" },
  meta: { flex: 1, textAlign: "left" },
  primaryText: { fontWeight: 600, fontSize: "14px", color: "#0f172a" },
  secondaryText: { fontSize: "12px", color: "#94a3b8" },
  statusPill: { fontSize: "11px", fontWeight: 700, color: "#1d4ed8", backgroundColor: "#e0e7ff", padding: "4px 10px", borderRadius: "999px" },
  feedback: { padding: "20px", fontSize: "14px", color: "#64748b" },
  detailPanel: { flex: 1, backgroundColor: "#fff", borderRadius: "16px", border: "1px solid #e2e8f0", padding: "28px", display: "flex", flexDirection: "column", gap: "20px", height: "calc(100vh - 160px)", overflow: "hidden" },
  detailHeader: { display: "flex", justifyContent: "space-between", gap: "16px", flexWrap: "wrap" },
  detailHeaderLeft: { display: "flex", gap: "16px", alignItems: "center" },
  largeAvatar: { width: "72px", height: "72px", borderRadius: "20px", objectFit: "cover", border: "2px solid #e2e8f0" },
  detailName: { fontSize: "20px", fontWeight: 700, color: "#0f172a" },
  detailSub: { fontSize: "13px", color: "#64748b" },
  detailChips: { display: "flex", gap: "12px", flexWrap: "wrap" },
  detailChip: { backgroundColor: "#f8fafc", borderRadius: "12px", padding: "10px 16px", fontSize: "13px", color: "#475569", display: "flex", flexDirection: "column", minWidth: "120px" },
  detailBody: { display: "grid", gridTemplateColumns: "minmax(280px, 360px) minmax(0, 1fr)", gap: "20px", flex: 1, minHeight: 0 },
  profileGrid: { display: "flex", flexDirection: "column", gap: "16px" },
  card: { border: "1px solid #f1f5f9", borderRadius: "16px", padding: "18px", minHeight: "150px" },
  cardTitle: { margin: 0, marginBottom: "12px", fontSize: "15px", color: "#0f172a" },
  cardText: { margin: 0, color: "#475569", fontSize: "14px", lineHeight: 1.6 },
  skillsWrap: { display: "flex", flexWrap: "wrap", gap: "8px" },
  skillChip: { padding: "6px 12px", borderRadius: "999px", backgroundColor: "#eef2ff", color: "#4338ca", fontWeight: 600, fontSize: "12px" },
  chatSection: { border: "1px solid #f1f5f9", borderRadius: "16px", flex: 1, display: "flex", flexDirection: "column", minHeight: 0 },
  messages: { flex: 1, padding: "20px", overflowY: "auto", display: "flex", flexDirection: "column", gap: "12px", minHeight: 0 },
  msgReceived: { alignSelf: "flex-start", maxWidth: "65%" },
  msgSent: { alignSelf: "flex-end", maxWidth: "65%", alignItems: "flex-end", display: "flex", flexDirection: "column" },
  bubbleReceived: { backgroundColor: "#f1f5f9", padding: "10px 14px", borderRadius: "12px 12px 12px 0", fontSize: "14px", color: "#1f2937" },
  bubbleSent: { backgroundColor: "#1d4ed8", color: "#fff", padding: "10px 14px", borderRadius: "12px 12px 0 12px", fontSize: "14px" },
  msgTime: { fontSize: "11px", color: "#94a3b8", marginTop: "4px" },
  emptyState: { textAlign: "center", color: "#94a3b8", padding: "30px 0" },
  inputArea: { borderTop: "1px solid #f1f5f9", padding: "16px", display: "flex", gap: "12px" },
  messageInput: { flex: 1, borderRadius: "12px", border: "1px solid #cbd5f5", padding: "12px", fontSize: "14px", outline: "none" },
  sendBtn: { width: "48px", borderRadius: "12px", border: "none", backgroundColor: "#1d4ed8", color: "#fff", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer" },
};

export default messagingStyles;
