# Generated by Django 5.2.8 on 2025-12-10 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_alter_projectproposal_freelancer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='proposal_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='proposals.projectproposal')),
            ],
        ),
    ]
