# Generated by Django 5.2.8 on 2025-12-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_proposalattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproposal',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('considering', 'Considering'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
